export const authStatus={
		LOGIN_REQUEST:"LOGIN_REQUEST",
		LOGIN_SUCCESS:"LOGIN_SUCCESS",
		LOGIN_FAILED:"LOGIN_FAILED"
}

export const regStatus={
	REG_REQUEST:"REG_REQUEST",
	REG_SUCCESS:"REG_SUCCESS",
	REG_FAILED:"REG_FAILED"
}

export const categoryStatus={
	CATEGORY_REQUEST:"CATEGORY_REQUEST",
	CATEGORY_SUCCESS:"CATEGORY_SUCCESS",
	CATEGORY_FAILED:"CATEGORY_FAILED"
}