export const authStatus={
		LOGIN_REQUEST:"LOGIN_REQUEST",
		LOGIN_SUCCESS:"LOGIN_SUCCESS",
		LOGIN_FAILED:"LOGIN_FAILED"
}

export const regStatus={
	REG_REQUEST:"REG_REQUEST",
	REG_SUCCESS:"REG_SUCCESS",
	REG_FAILED:"REG_FAILED"
}

export const otpStatus={
    OTP_REQUEST :"OTP_REQUEST",
    OTP_SUCCESS :"OTP_SUCCESS",
    OTP_FAILED :"OTP_FAILED"
}
export const generalStatus={
    GENERAL_REQUEST :"GENERAL_REQUEST",
    GENERAL_SUCCESS :"GENERAL_SUCCESS",
    GENERAL_FAILED :"GENERAL_FAILED"
}

export const categoryConstansts={ 
	GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
  ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
  ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
  ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE",
  UPDATE_CATEGORIES_REQUEST: "UPDATE_CATEGORIES_REQUEST",
  UPDATE_CATEGORIES_SUCCESS: "UPDATE_CATEGORIES_SUCCESS",
  UPDATE_CATEGORIES_FAILURE: "UPDATE_CATEGORIES_FAILURE",
  DELETE_CATEGORIES_REQUEST: "DELETE_CATEGORIES_REQUEST",
  DELETE_CATEGORIES_SUCCESS: "DELETE_CATEGORIES_SUCCESS",
  DELETE_CATEGORIES_FAILURE: "DELETE_CATEGORIES_FAILURE"
}

